$engine: 3
$onesync: on
name: NexusFiler
description: bubu
tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/servercfg/DevoNetwork
    ref: master
    subpath: server
    dest: ./server
