$engine: 3
$onesync: on
name: NF
description: NF

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/servercfg/AtlasCity/tree/main/server
    ref: master
    subpath: resources
    dest: ./resources

  # Download default server.cfg for FiveM
  - action: download_file
    url: https://github.com/servercfg/AtlasCity/blob/main/server/server.cfg
    path: ./server.cfg
