$engine: 3
$onesync: on
name: NexusRP
version: 3.3.0
author: Bubu65
description: bubu 

tasks:

  - action: download_github
    src: https://github.com/servercfg/DevoNetwork
    ref: main
    dest: ./resources
