$engine: 3
$onesync: on
name: NexusFiler
description: bubu
tasks: 
  # Download DevoNetwork
  - action: download_github
    src: https://github.com/servercfg/DevoNetwork.git
    ref: master
    subpath: resources
    dest: ./resources

  # Download server.cfg
  - action: download_file
    url: https://raw.githubusercontent.com/tabarra/CFX-Default-recipe/main/server.cfg
    path: ./server.cfg
