$engine: 3
$onesync: on
name: NexusFiler
description: bubu
tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/servercfg/DevoNetwork/tree/master/server
    ref: master
    subpath: resources
    dest: ./resources

  # Download default server.cfg for FiveM
  - action: download_file
    url: https://raw.githubusercontent.com/tabarra/CFX-Default-recipe/main/server.cfg
    path: ./server.cfg
