$engine: 3
$onesync: on
name: NexusFiler
description: bubu
tasks: 

  # Download DevoNetwork
  - action: download_github
    src: https://github.com/servercfg/DevoNetwork/tree/master/server
    ref: master
    subpath: resources
    dest: resources

  # Download server.cfg
  - action: download_file
    url:https://github.com/servercfg/DevoNetwork/tree/master/server
    path: ./server.cfg
